# Generated by Django 4.1.6 on 2023-02-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='categories',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
