# Generated by Django 4.1.6 on 2023-02-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='category',
        ),
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.ManyToManyField(to='home.gallerycategorie'),
        ),
    ]
