# Generated by Django 4.1.6 on 2023-02-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_project_category_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='preference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
