# Generated by Django 4.1.6 on 2023-02-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_contactus_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyNow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('street_address', models.CharField(max_length=255)),
                ('city_town', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('zip_code', models.BigIntegerField(blank=True, null=True)),
                ('preference', models.CharField(blank=True, max_length=20, null=True)),
                ('position', models.CharField(max_length=150)),
                ('resume', models.FileField(upload_to='Resume/')),
                ('cover_letter', models.FileField(upload_to='CoverLetter/')),
                ('education', models.TextField()),
                ('work_experience', models.TextField()),
                ('skills', models.TextField()),
                ('references', models.TextField()),
                ('additional_information', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
