# Generated by Django 4.1.6 on 2023-02-10 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_applynow'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertie',
            name='agent',
            field=models.ManyToManyField(blank=True, null=True, to='home.propertyagent'),
        ),
        migrations.AddField(
            model_name='propertyenquirie',
            name='property',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.propertie'),
        ),
    ]
