# Generated by Django 4.1.6 on 2023-02-10 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_propertie_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='propertie',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Interior', 'Interior')], default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='propertie',
            name='sale_or_rent',
            field=models.CharField(choices=[('sale', 'sale'), ('rent', 'rent')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='propertie',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.propertylocation'),
        ),
    ]
