# Generated by Django 4.1.6 on 2023-02-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_propertylocation_propertie_property_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertie',
            name='price',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='propertie',
            name='sub_title',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
