# Generated by Django 4.1.6 on 2023-02-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_propertie_price_propertie_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertie',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertie',
            name='sale_or_rent',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent')], default=None, max_length=50),
        ),
    ]
