# Generated by Django 4.1.6 on 2023-02-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_propertie_area_alter_propertie_sale_or_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertie',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
